### ISSUE TITLE
Fails to find a running firefox window

### ISSUE THREAD

**Issue by okapia** [siebenmann/ffox-remote#1]
Is this programme still relevant to recent firefox? I just get the message:
`ffox-remote: can't find a running Firefox window.`

Using xprop to get the firefox properties, I don't see any of the `_MOZILLA` ones that ffox-remote looks for. Using `xprop -spy` doesn't show relevant activity when using a full firefox to control my existing window. I've tried different window managers, the -U/-P/-G options and adding some print statements in the function that searches for firefox (which also implied a lack of `_MOZILLA_*` X properties). Have you got any suggestions on how I can go about debugging it?

**Comment by siebenmann** [comment]
It definitely should still work with recent Firefox versions; I use it with Firefox Nightly and Firefox 44, both on Fedora 23. However, a message of 'can't find a running Firefox window' means that I probably overlooked something in the code, because that means the code can't find the right Firefox window (which is unfortunately generally not the visible one).

What I would do is: first, use `xwininfo -root -tree` to find all Firefox windows. For each window, check its properties with xprop to find one with _MOZILLA_VERSION set; for me this is a 10x10 window that's hidden off the screen, which stands out. Use `xprop -spy -id ...` on this window while using remote control in Firefox itself to verify that the _MOZILLA_VERSION properties are being manipulated. Then look at the overall window hierarchy to find out why ffox-remote isn't finding it; it may be hidden away inside some other X window that's used for framing and control in a way that the code doesn't expect. If nothing jumps out but you found the window, put the xwininfo tree in this bug and I'll see if I can find something in it myself.

(For advanced debugging, you could modify the `findFirefox()` function to report the hex window IDs of every window it looked at to see how close it got to the window it needs to check. And if it claims it actually checked that window, we'll need to dig further.)

Oh, the other thing that would be handy is once you find the Firefox window, check a full xprop property dump to see what the value of _MOZILLA_VERSION is, and maybe put the full output here. I don't think Firefox changed the protocol version but ffox-remote is very picky, and there may be something else I'm doing wrong to find the window.

**Comment by okapia** [comment]
Thank you for the prompt and very helpful reply.

I had been using `xlsclients -al` to get all the window IDs which doesn't include hidden 10x10 windows. Having identified the correct window ID and, with a few printfs in `findFirefox()` and `propMatch()`, I was able to tracks down the cause which came down to mistakes on my part with the -G option (which I shouldn't have used) and somehow I never tried without it but with the correct -P option.

Thanks again, both for your help and for the very useful little tool.
